import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { beforeAll, afterAll, beforeEach, describe, it, expect } from "vitest";
import { meetingFeedbackWindow, resolveOperationalStage, scheduleOffsetMinutes } from "./meetingOperations";

const event = "00000000-0000-4000-8000-000000000001";
const group = "00000000-0000-4000-8000-000000000002";
const instance = "00000000-0000-4000-8000-000000000003";
const user = "00000000-0000-4000-8000-000000000004";
const stage = "00000000-0000-4000-8000-000000000005";
const second = "00000000-0000-4000-8000-000000000006";
let db: PGlite;
beforeAll(async () => {
  db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table ticket_templates(id uuid primary key default gen_random_uuid(),title text,visibility text,template_kind text,course_steps jsonb default '[]',stage_copy jsonb default '{}',short_description text,created_at timestamptz,updated_at timestamptz);
    create table ticket_instances(id uuid primary key,template_id uuid,title text,event_date date,event_time time,region text,
      max_participant_count int default 6,operation_code text,operation_note text,place_name text,address text,place_payload jsonb,updated_at timestamptz);
    create table ticket_participations(id bigint generated by default as identity primary key,user_id uuid,ticket_id text,ticket_template_id uuid,
      ticket_instance_id uuid,meeting_date date,status text,ticket_snapshot jsonb,invitation_id uuid,applied_at timestamptz,
      confirmed_at timestamptz,cancelled_at timestamptz,updated_at timestamptz,admin_note text);
    create table meeting_events(id uuid primary key default gen_random_uuid(),program_id uuid,short_description text,visibility text,title text,event_date date,starts_at time,region text,detail_snapshot jsonb default '{}',updated_at timestamptz);
    create table meeting_event_stages(id uuid primary key default gen_random_uuid(),event_id uuid,sequence int,title text,stage_type text,starts_at time,location_mode text,
      place_name text,address text,place_payload jsonb,updated_at timestamptz);
    create table meeting_groups(id uuid primary key,event_id uuid,code text,title text,legacy_ticket_instance_id uuid,status text,operation_note text,updated_at timestamptz);
    create table meeting_group_stage_locations(group_id uuid,stage_id uuid,place_name text,address text,place_payload jsonb,updated_at timestamptz,unique(group_id,stage_id));
    create table meeting_date_applications(id bigint primary key,user_id uuid,event_id uuid,application_group_id uuid,meeting_date date,meeting_time time,
      status text,assigned_ticket_instance_id uuid,ticket_participation_id bigint,assigned_group_id uuid,assigned_at timestamptz,confirmed_at timestamptz,
      cancelled_at timestamptz,admin_note text,updated_at timestamptz,deposit_status text,deposit_confirmed_at timestamptz,
      groble_merchant_uid text,groble_payment_event_id text,refund_completed_at timestamptz);
    create table ticket_user_interactions(user_id uuid,event_id uuid,ticket_instance_id uuid,status text,updated_at timestamptz);
    create table payment_transactions(id bigint primary key,user_id uuid,application_group_id uuid,payment_kind text,status text,cancelled_at timestamptz,updated_at timestamptz);
    grant all on all tables in schema public to service_role;
    grant all on all sequences in schema public to service_role;
  `);
  const source = readFileSync("supabase/migrations/20260701100000_ticket_domain_restructure.sql", "utf8");
  const start = source.indexOf("create or replace function public.set_ticket_participation_status(");
  await db.exec(source.slice(start, source.indexOf("$$;", start) + 3));
  for (const name of ["20260906050350_centralize_admin_waitlist_changes", "20260906053936_unify_meeting_operations"]) {
    if (name === "20260906053936_unify_meeting_operations") {
      await db.query("insert into meeting_groups(id,code,title) values($1,'7','7그룹'),($2,'RED','RED')", [event, group]);
    }
    await db.exec(readFileSync(`supabase/migrations/${name}.sql`, "utf8"));
  }
  await db.exec(readFileSync("supabase/migrations/20260908121432_event_owned_content.sql", "utf8"));
  expect((await db.query("select code,feedback_scope_key,starts_from_stage_sequence from meeting_groups order by code")).rows)
    .toEqual([{ code: "7", feedback_scope_key: "123", starts_from_stage_sequence: 2 },{ code: "RED", feedback_scope_key: null, starts_from_stage_sequence: 1 }]);
}, 30_000);
afterAll(async () => { await db?.close(); });
beforeEach(async () => {
  await db.exec("truncate ticket_instances,ticket_participations,meeting_events,meeting_groups,meeting_event_stages,meeting_group_stage_locations,meeting_date_applications,ticket_user_interactions,payment_transactions restart identity");
  await db.query("insert into meeting_events(id,title,event_date,starts_at,region,detail_snapshot) values($1,'Dinner','2026-09-06','18:00','서울',$2)", [event,JSON.stringify({ courseSteps: [{ title: "Old" }, { title: "Bar" }] })]);
  await db.query("insert into ticket_instances(id,event_date,event_time,place_name) values($1,'2026-09-06','18:00','old venue')", [instance]);
  await db.query("insert into meeting_groups(id,event_id,code,title,legacy_ticket_instance_id) values($1,$2,'RED','Red',$3)", [group,event,instance]);
  await db.query("insert into meeting_event_stages(id,event_id,sequence,title,stage_type,starts_at,location_mode,place_name) values($1,$2,1,'Dinner','meal','18:00','group_specific',null),($3,$2,2,'Bar','activity','19:15','shared','Second venue')", [stage,event,second]);
  await db.query("insert into meeting_group_stage_locations(group_id,stage_id,place_name,address) values($1,$2,'First venue','First address')", [group,stage]);
  await db.query("insert into ticket_participations(user_id,ticket_instance_id,status) values($1,$2,'approved')", [user,instance]);
  await db.query("insert into meeting_date_applications(id,user_id,event_id,application_group_id,meeting_date,meeting_time,status,assigned_ticket_instance_id,ticket_participation_id) values(10,$1,$2,$3,'2026-09-06','18:00','approved',$4,1)", [user,event,group,instance]);
});

describe("authoritative meeting operations", () => {
  it("never overwrites the dinner venue when the bar changes", async () => {
    await db.query("update meeting_event_stages set place_name='New bar' where id=$1", [second]);
    expect((await db.query("select place_name,address from ticket_instances")).rows[0]).toEqual({ place_name: "First venue", address: "First address" });
  });
  it("clears obsolete map payloads when the venue changes and honors hidden places", async () => {
    await db.exec("update meeting_group_stage_locations set place_payload='{\"link\":\"old\"}'");
    await db.exec("update meeting_group_stage_locations set place_name='Changed venue'");
    expect((await db.query("select place_name,place_payload from ticket_instances")).rows[0]).toEqual({ place_name: "Changed venue", place_payload: null });
    await db.query("update meeting_event_stages set location_mode='hidden' where id=$1", [stage]);
    expect((await db.query("select place_name,address from ticket_instances")).rows[0]).toEqual({ place_name: null, address: null });
  });
  it("moves schedules together while retaining the custom 75-minute interval", async () => {
    await db.exec("update meeting_events set starts_at='18:30',event_date='2026-09-13'");
    expect((await db.query("select starts_at::text from meeting_event_stages order by sequence")).rows).toEqual([{ starts_at: "18:30:00" },{ starts_at: "19:45:00" }]);
    expect((await db.query("select event_date::text,event_time::text from ticket_instances")).rows[0]).toEqual({ event_date: "2026-09-13", event_time: "18:30:00" });
    expect((await db.query("select meeting_date::text,meeting_time::text from meeting_date_applications")).rows[0]).toEqual({ meeting_date: "2026-09-13", meeting_time: "18:30:00" });
  });
  it("rolls back the original event edit if its legacy projection fails", async () => {
    await db.exec("alter table ticket_instances add constraint simulate_failure check(event_time <> '20:00')");
    try {
      await expect(db.exec("update meeting_events set starts_at='20:00'")).rejects.toThrow();
      expect((await db.query("select starts_at::text from meeting_events")).rows[0]).toEqual({ starts_at: "18:00:00" });
    } finally { await db.exec("alter table ticket_instances drop constraint simulate_failure"); }
  });
  it("keeps feedback scope and joining stage stable through group renames", async () => {
    await db.exec("update meeting_groups set feedback_scope_key='room-a',starts_from_stage_sequence=2");
    await db.exec("update meeting_groups set code='7',title='7그룹'");
    expect((await db.query("select feedback_scope_key,starts_from_stage_sequence from meeting_groups")).rows[0]).toEqual({ feedback_scope_key: "room-a", starts_from_stage_sequence: 2 });
  });
  it("rejects locations belonging to a different event", async () => {
    await db.query("insert into meeting_events(id) values($1)", [user]);
    await db.query("insert into meeting_event_stages(id,event_id,sequence) values($1,$2,1)", [user,user]);
    await expect(db.query("insert into meeting_group_stage_locations(group_id,stage_id) values($1,$2)", [group,user])).rejects.toThrow("같은 행사");
  });
  it("rolls back group metadata when the combined venue save fails", async () => {
    await db.exec("alter table meeting_group_stage_locations add constraint simulate_failure check(place_name <> 'failure')");
    try {
      await expect(db.query("select save_operational_group($1,$2,$3,$4)", [group, JSON.stringify({ code: "BLUE" }), stage, JSON.stringify({ placeName: "failure" })])).rejects.toThrow();
      expect((await db.query("select code from meeting_groups")).rows[0]).toEqual({ code: "RED" });
    } finally { await db.exec("alter table meeting_group_stage_locations drop constraint simulate_failure"); }
  });
  it("projects stage title changes into the public invitation in the same edit", async () => {
    await db.query("update meeting_event_stages set title='Updated dinner' where id=$1", [stage]);
    expect((await db.query("select detail_snapshot #>> '{courseSteps,0,title}' as title from meeting_events")).rows[0]).toEqual({ title: "Updated dinner" });
  });
});

describe("shared participation writes", () => {
  it("updates the application when removing a member through ticket administration", async () => {
    await db.query("select admin_set_instance_member_status($1,$2,'not_selected')", [instance,user]);
    expect((await db.query("select status from meeting_date_applications")).rows[0]).toEqual({ status: "not_selected" });
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "not_selected" });
  });
  it("rejects a user's cancellation after concurrent approval and checks ownership", async () => {
    await expect(db.query("select cancel_own_meeting_application(10,$1)", [user])).rejects.toThrow("현재 상태");
    await expect(db.query("select cancel_own_meeting_application(10,$1)", [event])).rejects.toThrow("찾지 못");
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("rolls back cancellation if reopening the interaction fails", async () => {
    await db.exec("update meeting_date_applications set status='waitlisted'");
    await db.query("insert into ticket_user_interactions(user_id,event_id,status) values($1,$2,'waiting')", [user,event]);
    await db.exec("alter table ticket_user_interactions add constraint simulate_failure check(status <> 'open')");
    try {
      await expect(db.query("select cancel_own_meeting_application(10,$1)", [user])).rejects.toThrow();
      expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
    } finally { await db.exec("alter table ticket_user_interactions drop constraint simulate_failure"); }
    const saved = (await db.query<{ cancel_own_meeting_application: { status: string } }>("select cancel_own_meeting_application(10,$1)", [user])).rows[0];
    expect(saved.cancel_own_meeting_application.status).toBe("cancelled");
    expect((await db.query("select status from ticket_user_interactions")).rows[0]).toEqual({ status: "open" });
  });
  it("does not downgrade an approval after the checkout screen's stale lookup", async () => {
    await db.exec("update meeting_date_applications set status='payment_pending'");
    await db.query("select prepare_checkout_participation(10,$1,$2,'{}',null)", [instance,user]);
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("does not downgrade approved participation on delayed payment delivery", async () => {
    await db.exec("update meeting_date_applications set status='payment_pending'");
    await db.query("select advance_paid_meeting_applications($1,$2,null,'merchant','event',now(),true)", [user,group]);
    expect((await db.query("select status,deposit_status from meeting_date_applications")).rows[0]).toEqual({ status: "approved", deposit_status: "confirmed" });
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("rolls back a refund including participant changes if the transaction save fails", async () => {
    await db.query("insert into payment_transactions(id,user_id,application_group_id,payment_kind,status) values(1,$1,$2,'one_time','completed')", [user,group]);
    await db.exec("alter table payment_transactions add constraint simulate_failure check(status <> 'cancelled')");
    try {
      await expect(db.query("select cancel_one_time_payment(1,now())")).rejects.toThrow();
      expect((await db.query("select status from meeting_date_applications")).rows[0]).toEqual({ status: "approved" });
      expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
    } finally { await db.exec("alter table payment_transactions drop constraint simulate_failure"); }
    await db.query("select cancel_one_time_payment(1,now())");
    expect((await db.query("select status,deposit_status from meeting_date_applications")).rows[0]).toEqual({ status: "cancelled", deposit_status: "refunded" });
  });
  it("blocks browser execution of the new write functions", async () => {
    await db.exec("set role authenticated");
    try {
      await expect(db.query("select cancel_own_meeting_application(10,$1)", [user])).rejects.toThrow("permission denied");
      await expect(db.query("select cancel_one_time_payment(1,now())")).rejects.toThrow("permission denied");
      await expect(db.query("select admin_set_instance_member_status($1,$2,'approved')", [instance,user])).rejects.toThrow("permission denied");
      await expect(db.query("select advance_paid_meeting_applications($1,$2,null,'m','e',now(),true)", [user,group])).rejects.toThrow("permission denied");
    } finally { await db.exec("reset role"); }
  });
  it("runs projections with the same service role used by the API", async () => {
    await db.exec("set role service_role");
    try { await db.exec("update meeting_events set starts_at='18:30'"); }
    finally { await db.exec("reset role"); }
    expect((await db.query("select event_time::text from ticket_instances")).rows[0]).toEqual({ event_time: "18:30:00" });
  });
});

it("uses operational times across midnight and does not inherit a missing group venue", () => {
  expect(scheduleOffsetMinutes("23:30","00:45")).toBe(75);
  const resolved = resolveOperationalStage({ id: stage,event_id:event,sequence:2,title:"Bar",stage_type:"feedback",starts_at:"22:00",
    location_mode:"group_specific",place_name:"stale common venue",address:"old",place_payload:null },"18:00");
  expect(resolved.placeName).toBeNull();
  const window = meetingFeedbackWindow(new Date("2026-09-06T18:00:00+09:00"),[resolved]);
  expect(window.opensAt.toISOString()).toBe("2026-09-06T13:00:00.000Z");
  expect(window.closesAt.getTime()-window.opensAt.getTime()).toBe(24*3600_000);
});

describe("event-owned content",()=>{
  it("creates an event with its common waiting journey without a program",async()=>{
    const result=await db.query<{id:string}>("select create_standalone_meeting_event('New','2026-09-30','18:00','서울',$1) as id",[JSON.stringify({courseSteps:[{title:'Dinner',openOffsetMinutes:0},{title:'Games',openOffsetMinutes:90}],stageCopy:{}})]);
    const id=result.rows[0].id;
    expect((await db.query("select count(*)::int as count from meeting_event_stages where event_id=$1",[id])).rows[0]).toEqual({count:3});
    expect((await db.query("select t.title from meeting_events e join ticket_templates t on t.id=e.program_id where e.id=$1",[id])).rows[0]).toEqual({title:'New'});
  });
  it("keeps assigned ticket content in sync with the event and preserves assignment",async()=>{
    await db.query("update ticket_participations set ticket_template_id=(select program_id from meeting_events where id=$1),ticket_snapshot=$2",[event,JSON.stringify({stageCopy:{applied:'old'}})]);
    await db.query("select update_event_stage_copy($1,$2)",[event,JSON.stringify({applied:'new'})]);
    expect((await db.query("select t.stage_copy->>'applied' as copy from meeting_events e join ticket_templates t on t.id=e.program_id where e.id=$1",[event])).rows[0]).toEqual({copy:'new'});
    expect((await db.query("select status,ticket_snapshot #>> '{stageCopy,applied}' as copy from ticket_participations")).rows[0]).toEqual({status:'approved',copy:'new'});
    await db.query("select update_event_stage_copy($1,'{}')",[event]);
    expect((await db.query("select ticket_snapshot->'stageCopy' as copy from ticket_participations")).rows[0]).toEqual({copy:{}});
  });
});
