import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { beforeAll, afterAll, beforeEach, describe, it, expect } from "vitest";
import { calculateMembershipEndDate } from "../src/features/membership/membershipTypes";
const user = "00000000-0000-4000-8000-000000000001";
const migration =
  "supabase/migrations/20260906073658_atomic_membership_payment_effects.sql";
let db: PGlite;
let today: string;
const one = async (sql: string, args: unknown[] = []) =>
  (await db.query(sql, args)).rows[0] as Record<string, any>;
beforeAll(async () => {
  db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create table ticket_instances(id uuid primary key,template_id uuid,title text,event_date date,event_time time,region text,
      max_participant_count int default 6,operation_code text,operation_note text,place_name text,address text,place_payload jsonb,updated_at timestamptz);
    create table ticket_participations(id bigint generated by default as identity primary key,user_id uuid,ticket_id text,ticket_template_id uuid,
      ticket_instance_id uuid,meeting_date date,status text,ticket_snapshot jsonb,invitation_id uuid,applied_at timestamptz,
      confirmed_at timestamptz,cancelled_at timestamptz,updated_at timestamptz,admin_note text);
    create table meeting_events(id uuid primary key,title text,event_date date,starts_at time,region text,detail_snapshot jsonb default '{}',updated_at timestamptz);
    create table meeting_event_stages(id uuid primary key,event_id uuid,sequence int,title text,stage_type text,starts_at time,location_mode text,
      place_name text,address text,place_payload jsonb,updated_at timestamptz);
    create table meeting_groups(id uuid primary key,event_id uuid,code text,title text,legacy_ticket_instance_id uuid,status text,operation_note text,updated_at timestamptz);
    create table meeting_group_stage_locations(group_id uuid,stage_id uuid,place_name text,address text,place_payload jsonb,updated_at timestamptz,unique(group_id,stage_id));
    create table meeting_date_applications(id bigint primary key,user_id uuid,event_id uuid,application_group_id uuid,meeting_date date,meeting_time time,
      status text,assigned_ticket_instance_id uuid,ticket_participation_id bigint,assigned_group_id uuid,assigned_at timestamptz,confirmed_at timestamptz,
      cancelled_at timestamptz,admin_note text,updated_at timestamptz,deposit_status text,deposit_confirmed_at timestamptz,
      groble_merchant_uid text,groble_payment_event_id text,refund_completed_at timestamptz);
    create table ticket_user_interactions(user_id uuid,event_id uuid,ticket_instance_id uuid,status text,updated_at timestamptz);
grant all on all tables in schema public to service_role;
    grant all on all sequences in schema public to service_role;

 create table profiles(user_id uuid primary key,name text,nickname text, membership_status text,membership_plan text,
 membership_start_date date,membership_end_date date,membership_updated_at timestamptz);
 create table groble_webhook_events(merchant_uid text,event_type text,event_id text unique,payload jsonb);
 create table deposit_message_registrations(user_id uuid primary key,first_ticket_instance_id uuid);
 alter table meeting_date_applications add created_at timestamptz default now();
 alter table ticket_user_interactions add opened_at timestamptz,add responded_at timestamptz,
 add payment_started_at timestamptz,add payment_confirmed_at timestamptz;
 `);
  const base = readFileSync(
    "supabase/migrations/20260729120000_unified_payments_and_membership_intents.sql",
    "utf8",
  );
  await db.exec(
    base.slice(0, base.indexOf("alter table public.groble_webhook_events")),
  );
  await db.exec(
    "alter table membership_payment_intents add meeting_date_application_id bigint",
  );
  const oldStatus = readFileSync(
    "supabase/migrations/20260701100000_ticket_domain_restructure.sql",
    "utf8",
  );
  const start = oldStatus.indexOf(
    "create or replace function public.set_ticket_participation_status(",
  );
  await db.exec(oldStatus.slice(start, oldStatus.indexOf("$$;", start) + 3));
  for (const name of [
    "20260906050350_centralize_admin_waitlist_changes",
    "20260906053936_unify_meeting_operations",
  ])
    await db.exec(readFileSync("supabase/migrations/" + name + ".sql", "utf8"));
  await db.exec(readFileSync(migration, "utf8"));
  await db.exec(
    readFileSync(
      "supabase/migrations/20260907055229_handle_groble_refund_events.sql",
      "utf8",
    ),
  );
  await db.exec(
    "grant usage on schema public to service_role; grant all on all tables in schema public to service_role; grant usage,select on all sequences in schema public to service_role",
  );
  today = (
    await one("select (now() at time zone 'Asia/Seoul')::date::text as day")
  ).day;
}, 30000);
afterAll(async () => {
  await db.close();
});
beforeEach(async () => {
  await db.exec(
    "truncate membership_payment_effects,payment_transactions,membership_payment_intents,profiles,meeting_date_applications,ticket_user_interactions,deposit_message_registrations,groble_webhook_events restart identity cascade",
  );
  await db.query("insert into profiles(user_id,name) values($1,'Original')", [
    user,
  ]);
});
async function intent(
  plan = "one_month",
  credit = 0,
  app: number | null = null,
) {
  return (
    await one(
      "insert into membership_payment_intents(user_id,plan,expected_amount,credit_amount,opened_at,expires_at,status,meeting_date_application_id) values($1,$2,10000,$3,now()-interval '1 day',now()+interval '1 day','superseded',$4) returning id",
      [user, plan, credit, app],
    )
  ).id;
}
async function pay(
  id: number,
  event = "payment-1",
  merchant = event,
  paid = today + "T12:00:00+09:00",
  amount = 10000,
) {
  return (
    await one(
      "select public.apply_membership_payment($1,$2,$3,$4,$5,$6,'Updated') as result",
      [user, id, event, merchant, amount, paid],
    )
  ).result;
}
async function cancel(id: number) {
  return (
    await one(
      "select public.cancel_membership_payment($1,now()+interval '2 days') as result",
      [id],
    )
  ).result;
}
describe("atomic membership payment effects", () => {
  it("commits membership, intent, transaction, linked application, interaction and counter together", async () => {
    await db.query(
      "insert into meeting_date_applications(id,user_id,status,meeting_date,deposit_status) values(10,$1,'payment_pending',$2,'payment_pending')",
      [user, today],
    );
    await db.query(
      "insert into ticket_user_interactions(user_id,ticket_instance_id,status) values($1,$2,'payment_pending')",
      [user, user],
    );
    const id = await intent("one_month", 0, 10);
    const result = await pay(id);
    expect(result.outcome).toBe("applied");
    expect(
      await one("select membership_end_date::text as e,name from profiles"),
    ).toEqual({
      e: calculateMembershipEndDate(today, "one_month"),
      name: "Updated",
    });
    expect(
      (await one("select status from membership_payment_intents")).status,
    ).toBe("completed");
    expect(
      (await one("select status from meeting_date_applications")).status,
    ).toBe("waitlisted");
    expect(
      (await one("select status from ticket_user_interactions")).status,
    ).toBe("payment_confirmed");
    expect(
      (
        await one(
          "select count(*)::int as n from deposit_message_registrations",
        )
      ).n,
    ).toBe(1);
  });
  it("rolls all writes back when a late receipt write fails, and retries cleanly", async () => {
    await db.query(
      "insert into meeting_date_applications(id,user_id,status,meeting_date,deposit_status) values(10,$1,'payment_pending',$2,'payment_pending')",
      [user, today],
    );
    const id = await intent("one_month", 0, 10);
    await db.exec(
      "create function fail_receipt() returns trigger language plpgsql as $$begin raise exception 'receipt failure'; end;$$; create trigger fail_receipt before insert on membership_payment_effects for each row execute function fail_receipt()",
    );
    try {
      await expect(pay(id)).rejects.toThrow("receipt failure");
      expect(
        (await one("select count(*)::int as n from payment_transactions")).n,
      ).toBe(0);
      expect(
        (await one("select membership_status from profiles")).membership_status,
      ).toBeNull();
      expect(
        (await one("select status from membership_payment_intents")).status,
      ).toBe("superseded");
      expect(
        (await one("select status from meeting_date_applications")).status,
      ).toBe("payment_pending");
      expect(
        (
          await one(
            "select count(*)::int as n from deposit_message_registrations",
          )
        ).n,
      ).toBe(0);
    } finally {
      await db.exec(
        "drop trigger fail_receipt on membership_payment_effects; drop function fail_receipt()",
      );
    }
    expect((await pay(id)).outcome).toBe("applied");
  });
  it("does not extend twice for duplicate events or another event for the same charge", async () => {
    const id = await intent();
    await pay(id);
    const before = await one(
      "select membership_end_date::text as e from profiles",
    );
    expect((await pay(id)).outcome).toBe("already_applied");
    expect((await pay(id, "new-event", "payment-1")).outcome).toBe(
      "already_applied",
    );
    expect(
      await one("select membership_end_date::text as e from profiles"),
    ).toEqual(before);
    expect(
      (await one("select count(*)::int as n from payment_transactions")).n,
    ).toBe(1);
  });
  it("rejects a different charge reusing the same intent and a wrong amount", async () => {
    const id = await intent();
    await expect(pay(id, "p", "p", undefined, 9)).rejects.toThrow("amount");
    await pay(id);
    await expect(pay(id, "other", "other")).rejects.toThrow(
      "identity conflict",
    );
  });
  it.each(["one_month", "three_months", "six_months"] as const)(
    "preserves month-end rules for %s",
    async (plan) => {
      await db.query(
        "insert into meeting_date_applications(id,user_id,status,meeting_date) values(10,$1,'waitlisted','2028-01-31')",
        [user],
      );
      await pay(await intent(plan, 0, 10));
      expect(
        (await one("select membership_end_date::text as e from profiles")).e,
      ).toBe(calculateMembershipEndDate("2028-01-31", plan));
    },
  );
  it("extends active renewals from the day after expiry and preserves their original start", async () => {
    await pay(await intent());
    const current = await one(
      "select membership_start_date::text as s,membership_end_date::text as e from profiles",
    );
    const base = (
      await one("select (membership_end_date+1)::text as b from profiles")
    ).b;
    const result = await pay(await intent("three_months"), "renewal");
    expect(result.payment_kind).toBe("membership_renewal");
    expect(
      await one(
        "select membership_start_date::text as s,membership_end_date::text as e from profiles",
      ),
    ).toEqual({
      s: current.s,
      e: calculateMembershipEndDate(base, "three_months"),
    });
  });
  it("retains upgrade policy and does not treat expired membership as an active renewal", async () => {
    await pay(await intent());
    expect(
      (await pay(await intent("six_months", 5000), "upgrade")).payment_kind,
    ).toBe("membership_upgrade");
    expect(
      (await one("select membership_end_date::text as e from profiles")).e,
    ).toBe(calculateMembershipEndDate(today, "six_months"));
    await db.exec("update profiles set membership_end_date=current_date-1");
    await pay(await intent(), "expired-renewal");
    expect(
      (await one("select membership_end_date::text as e from profiles")).e,
    ).toBe(calculateMembershipEndDate(today, "one_month"));
  });
  it("protects a newer payment when cancelling an older one, even with identical occurrence timestamps", async () => {
    const first = await pay(await intent());
    const last = await pay(await intent(), "renewal");
    expect((await cancel(first.transaction_id)).revoked_access).toBe(false);
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("active");
    expect((await cancel(last.transaction_id)).revoked_access).toBe(true);
    expect((await cancel(last.transaction_id)).outcome).toBe(
      "already_cancelled",
    );
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("cancelled");
  });
  it("does not reactivate refunded membership on a late completion callback", async () => {
    const id = await intent(),
      result = await pay(id);
    await cancel(result.transaction_id);
    expect((await pay(id)).outcome).toBe("cancelled");
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("cancelled");
  });
  it("preserves explicit operator changes when a payment is cancelled", async () => {
    const result = await pay(await intent());
    await db.exec(
      "update profiles set membership_end_date=membership_end_date+10",
    );
    expect((await cancel(result.transaction_id)).revoked_access).toBe(false);
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("active");
  });
  it("rolls cancellation back if an intent update fails", async () => {
    const result = await pay(await intent());
    await db.exec(
      "create function fail_cancel() returns trigger language plpgsql as $$begin if new.status='cancelled' then raise exception 'cancel failure'; end if; return new; end;$$; create trigger fail_cancel before update on membership_payment_intents for each row execute function fail_cancel()",
    );
    try {
      await expect(cancel(result.transaction_id)).rejects.toThrow(
        "cancel failure",
      );
      expect(
        (await one("select status from payment_transactions")).status,
      ).toBe("completed");
      expect(
        (await one("select membership_status from profiles")).membership_status,
      ).toBe("active");
      expect(
        (await one("select cancelled_at from membership_payment_effects"))
          .cancelled_at,
      ).toBeNull();
    } finally {
      await db.exec(
        "drop trigger fail_cancel on membership_payment_intents; drop function fail_cancel()",
      );
    }
  });
  it("holds an out-of-order completion and cancellation-first delivery for review", async () => {
    await db.exec(
      "update profiles set membership_updated_at=now()+interval '2 days'",
    );
    const id = await intent();
    await expect(pay(id)).rejects.toThrow("Older membership payment");
    await db.exec(
      "update profiles set membership_updated_at=null; insert into groble_webhook_events(merchant_uid,event_type) values('payment-1','subscription_payment.cancelled')",
    );
    await expect(pay(id)).rejects.toThrow("cancellation arrived");
    expect(
      (await one("select count(*)::int as n from payment_transactions")).n,
    ).toBe(0);
  });
  it("does not replay a pre-migration completed period", async () => {
    const id = await intent(),
      result = await pay(id);
    await db.exec("delete from membership_payment_effects");
    await expect(pay(id)).rejects.toThrow("no application receipt");
    expect((await cancel(result.transaction_id)).revoked_access).toBe(true);
  });
  it("runs through service_role but blocks anonymous and signed-in clients", async () => {
    const id = await intent();
    await db.exec("set role service_role");
    try {
      expect((await pay(id)).outcome).toBe("applied");
    } finally {
      await db.exec("reset role");
    }
    expect(
      await one(
        "select has_function_privilege('anon','public.apply_membership_payment(uuid,bigint,text,text,integer,timestamptz,text)','execute') as a,has_function_privilege('authenticated','public.cancel_membership_payment(bigint,timestamptz)','execute') as u",
      ),
    ).toEqual({ a: false, u: false });
  });
});

it("accepts the existing upgrade credit amount convention", async () => {
  const id = await intent("three_months", 5000);
  expect(
    (await pay(id, "upgrade-credit", "upgrade-credit", undefined, 5000))
      .payment_kind,
  ).toBe("membership_upgrade");
});
async function refundEvent(
  merchant = "payment-1",
  partial = false,
  amount = 10000,
) {
  await db.query(
    `insert into groble_webhook_events(event_id,event_type,merchant_uid,payload)
    values('refund-1','subscription_payment.refunded',$1,$2)`,
    [
      merchant,
      JSON.stringify({
        data: {
          object: {
            refund: {
              partialRefund: partial,
              amount,
              currency: "KRW",
              refundedAt: today + "T13:00:00+09:00",
            },
          },
        },
      }),
    ],
  );
}
async function refund() {
  return (await one("select apply_groble_refund('refund-1') as result")).result;
}
describe("stored refund events", () => {
  async function setup() {
    await db.query(
      "insert into meeting_date_applications(id,user_id,status,meeting_date) values(10,$1,'payment_pending',$2)",
      [user, today],
    );
    await pay(await intent("one_month", 0, 10));
    await refundEvent();
  }
  it("cancels the paid upcoming application and membership atomically, without cancelling independent bookings", async () => {
    await setup();
    await db.query(
      "insert into meeting_date_applications(id,user_id,status,meeting_date) values(11,$1,'waitlisted',$2)",
      [user, today],
    );
    expect((await refund()).cancelled_applications).toEqual([10]);
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("cancelled");
    expect(
      (
        await one(
          "select status,refund_completed_at from meeting_date_applications where id=10",
        )
      ).status,
    ).toBe("cancelled");
    expect(
      (await one("select status from meeting_date_applications where id=11"))
        .status,
    ).toBe("waitlisted");
    expect((await refund()).cancelled_applications).toEqual([]);
    expect((await one("select status from payment_transactions")).status).toBe(
      "cancelled",
    );
  });
  it.each([
    [true, 10000],
    [false, 5000],
  ])(
    "rejects partial or inconsistent refunds (%s %s)",
    async (partial, amount) => {
      await pay(await intent());
      await refundEvent("payment-1", partial, amount);
      await expect(refund()).rejects.toThrow(/review/);
      expect(
        (await one("select status from payment_transactions")).status,
      ).toBe("completed");
      expect(
        (await one("select membership_status from profiles")).membership_status,
      ).toBe("active");
    },
  );
  it("preserves replacement membership and its application when an older charge is refunded", async () => {
    await setup();
    await pay(
      await intent("one_month", 0, 10),
      "payment-2",
      "payment-2",
      today + "T12:30:00+09:00",
    );
    expect((await refund()).cancelled_applications).toEqual([]);
    expect(
      (await one("select membership_status from profiles")).membership_status,
    ).toBe("active");
    expect(
      (await one("select status from meeting_date_applications where id=10"))
        .status,
    ).toBe("waitlisted");
  });
  it("rolls membership cancellation back if linked application cleanup fails", async () => {
    await setup();
    await db.exec(
      "create function fail_refund_app() returns trigger language plpgsql as $$begin raise exception 'app refund failure'; end;$$; create trigger fail_refund_app before update on meeting_date_applications for each row execute function fail_refund_app()",
    );
    try {
      await expect(refund()).rejects.toThrow("app refund failure");
      expect(
        (await one("select status from payment_transactions")).status,
      ).toBe("completed");
      expect(
        (await one("select membership_status from profiles")).membership_status,
      ).toBe("active");
    } finally {
      await db.exec(
        "drop trigger fail_refund_app on meeting_date_applications; drop function fail_refund_app()",
      );
    }
  });
  it("blocks completion received after a stored refund notification", async () => {
    const id = await intent();
    await refundEvent();
    await expect(pay(id)).rejects.toThrow(/review/i);
    expect(
      (await one("select count(*)::int as n from payment_transactions")).n,
    ).toBe(0);
  });
});
