import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

const userId = "00000000-0000-4000-8000-000000000001";
const instanceId = "00000000-0000-4000-8000-000000000002";
const tokenA = "00000000-0000-4000-8000-000000000003";
const tokenB = "00000000-0000-4000-8000-000000000004";
let db: PGlite;

beforeAll(async () => {
  db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table ticket_instances(id uuid primary key, event_date date, template_id uuid, max_participant_count int);
    create table ticket_participations(
      id bigint generated by default as identity primary key, user_id uuid, ticket_id text,
      ticket_template_id uuid, ticket_instance_id uuid, meeting_date date, status text,
      ticket_snapshot jsonb, invitation_id uuid, applied_at timestamptz, confirmed_at timestamptz,
      cancelled_at timestamptz, updated_at timestamptz, feedback_completed_at timestamptz, admin_note text);
    create table meeting_date_applications(id bigint primary key, user_id uuid, status text,
      assigned_ticket_instance_id uuid, ticket_participation_id bigint, updated_at timestamptz,
      meeting_date date default '2026-09-06', assigned_group_id uuid, assigned_at timestamptz, confirmed_at timestamptz, cancelled_at timestamptz, admin_note text);
    create table meeting_groups(id uuid primary key, legacy_ticket_instance_id uuid, status text, updated_at timestamptz);
    create table meeting_feedback(waitlist_id bigint unique, user_id uuid, ticket_instance_id uuid,
      ticket_template_id uuid, ticket_snapshot jsonb, selected_member_ids uuid[], member_feedback jsonb,
      place_feedback jsonb, updated_at timestamptz);
    create table groble_webhook_events(id bigint generated always as identity primary key,
      event_id text unique, idempotency_key text unique, processing_status text default 'received', updated_at timestamptz);
    grant insert, update, select on meeting_feedback to authenticated;
    grant all on all tables in schema public to service_role;
    grant all on all sequences in schema public to service_role;
  `);
  const original = readFileSync("supabase/migrations/20260701100000_ticket_domain_restructure.sql", "utf8");
  const start = original.indexOf("create or replace function public.set_ticket_participation_status(");
  const end = original.indexOf("$$;", start) + 3;
  await db.exec(original.slice(start, end));
  // Exercise the real reservation inheritance trigger when moving participants.
  await db.exec(readFileSync("supabase/migrations/20260828095458_inherit_reservation_names_for_late_participants.sql", "utf8"));
  for (const file of ["20260906031238_harden_feedback_and_application_writes.sql", "20260906031248_recover_interrupted_webhooks.sql", "20260906050350_centralize_admin_waitlist_changes.sql"]) {
    await db.exec(readFileSync(`supabase/migrations/${file}`, "utf8"));
  }
}, 30_000);

beforeEach(async () => {
  await db.exec("truncate ticket_participations, meeting_date_applications, ticket_instances, meeting_feedback, groble_webhook_events, meeting_groups restart identity;");
  await db.query("insert into ticket_instances values ($1, '2026-09-06', null, 6)", [instanceId]);
  await db.query("insert into ticket_participations(user_id,ticket_instance_id,status,ticket_snapshot) values ($1,$2,'approved', $3)", [userId, instanceId, JSON.stringify({ reservationName: "예약 유지" })]);
  await db.query("insert into meeting_date_applications(id,user_id,status,assigned_ticket_instance_id) values (10,$1,'waitlisted',$2)", [userId, instanceId]);
});
afterAll(async () => { await db?.close(); });

const ensure = () => db.query("select ensure_application_participation(10,$1,$2,'{}') as id", [userId, instanceId]);
const save = () => db.query("select save_validated_meeting_feedback(1,$1,$2,null,'{}','{}','{}','{}')", [userId, instanceId]);

describe("atomic participation and feedback writes", () => {
  it("preserves confirmed status and reservation snapshot on repeated application linking", async () => {
    await ensure(); await ensure();
    const row = (await db.query<{ status: string; ticket_snapshot: object }>("select status,ticket_snapshot from ticket_participations where id=1")).rows[0];
    expect(row).toEqual({ status: "approved", ticket_snapshot: { reservationName: "예약 유지" } });
    expect((await db.query("select ticket_participation_id from meeting_date_applications where id=10")).rows[0]).toEqual({ ticket_participation_id: 1 });
  });
  it("does not touch an application approved while the request was in flight", async () => {
    await db.exec("update meeting_date_applications set status='approved',ticket_participation_id=1");
    await ensure();
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("rejects a different ticket without changing the application", async () => {
    await expect(db.query("select ensure_application_participation(10,$1,$2,'{}')", [userId, tokenB])).rejects.toThrow("mismatch");
    expect((await db.query("select ticket_participation_id from meeting_date_applications")).rows[0]).toEqual({ ticket_participation_id: null });
  });
  it("saves feedback and marks completion once", async () => {
    await save(); await save();
    expect((await db.query("select count(*)::int as count from meeting_feedback")).rows[0]).toEqual({ count: 1 });
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "feedback_done" });
  });
  it("rolls back feedback if completion fails", async () => {
    await db.exec("alter table ticket_participations add constraint simulate_failure check(status <> 'feedback_done')");
    try {
      await expect(save()).rejects.toThrow();
      expect((await db.query("select count(*)::int as count from meeting_feedback")).rows[0]).toEqual({ count: 0 });
    } finally { await db.exec("alter table ticket_participations drop constraint simulate_failure"); }
  });
  it("blocks browser writes and direct invocation of server-only functions", async () => {
    await db.exec("set role authenticated");
    try {
      await expect(db.query("insert into meeting_feedback(waitlist_id,user_id) values(1,$1)", [userId])).rejects.toThrow("permission denied");
      await expect(db.query("update meeting_feedback set member_feedback='{}'")).rejects.toThrow("permission denied");
      await expect(save()).rejects.toThrow("permission denied");
      await expect(ensure()).rejects.toThrow("permission denied");
    } finally { await db.exec("reset role"); }
  });
});

const claim = async (token = tokenA, eventId = "event-1", key = "key-1") =>
  (await db.query<{ outcome: string; event_key: string | null }>("select * from claim_groble_webhook_event($1,$2,$3)", [eventId,key,token])).rows[0];

const editApplication = (patch: object, id = 10) => db.query(
  "select admin_update_meeting_application($1,$2)", [id, JSON.stringify(patch)],
);
const editParticipation = (patch: object) => db.query(
  "select admin_update_ticket_participation(1,$1)", [JSON.stringify(patch)],
);
const batch = (ids: number[], confirm: boolean, onlyCurrent = false) => db.query(
  "select admin_assign_waitlist_applications($1,$2,$3,$4)", [ids, instanceId, confirm, onlyCurrent],
);

describe("admin waitlist commands", () => {
  it("approves and cancels application/participation together, preserving the snapshot", async () => {
    await editApplication({ status: "approved", adminNote: "confirmed" });
    await editApplication({ status: "cancelled" });
    expect((await db.query("select status,admin_note,ticket_participation_id from meeting_date_applications")).rows[0])
      .toEqual({ status: "cancelled", admin_note: "confirmed", ticket_participation_id: 1 });
    expect((await db.query("select status,ticket_snapshot from ticket_participations where id=1")).rows[0])
      .toEqual({ status: "cancelled", ticket_snapshot: { reservationName: "예약 유지" } });
    await editApplication({ status: "approved" });
    expect((await db.query("select cancelled_at from ticket_participations where id=1")).rows[0]).toEqual({ cancelled_at: null });
  });
  it("rolls back participation changes when application saving fails", async () => {
    await db.exec("alter table meeting_date_applications add constraint simulate_save_failure check(status <> 'approved')");
    try {
      await db.exec("update ticket_participations set status='waitlisted'");
      await expect(editApplication({ status: "approved" })).rejects.toThrow();
      expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "waitlisted" });
      expect((await db.query("select ticket_participation_id from meeting_date_applications")).rows[0]).toEqual({ ticket_participation_id: null });
    } finally { await db.exec("alter table meeting_date_applications drop constraint simulate_save_failure"); }
  });
  it("moves, changes status and saves the note in the same command", async () => {
    await editApplication({ status: "approved" });
    await db.query("insert into ticket_instances values($1,'2026-09-06',null,6)", [tokenB]);
    await db.query("insert into meeting_groups(id,legacy_ticket_instance_id) values($1,$2)", [tokenA,tokenB]);
    await editApplication({ ticketInstanceId: tokenB, status: "on_hold", adminNote: "moved" });
    expect((await db.query("select status from ticket_participations where id=1")).rows[0]).toEqual({ status: "cancelled" });
    expect((await db.query("select status,ticket_snapshot from ticket_participations where ticket_instance_id=$1", [tokenB])).rows[0])
      .toEqual({ status: "on_hold", ticket_snapshot: {} });
    expect((await db.query("select status,admin_note,assigned_group_id from meeting_date_applications")).rows[0])
      .toEqual({ status: "on_hold", admin_note: "moved", assigned_group_id: tokenA });
  });
  it("does not resurrect cancelled members on move-only requests", async () => {
    await editApplication({ status: "approved" }); await editApplication({ status: "cancelled" });
    await db.query("insert into ticket_instances values($1,'2026-09-06',null,6)", [tokenB]);
    await editApplication({ ticketInstanceId: tokenB });
    expect((await db.query("select status from meeting_date_applications")).rows[0]).toEqual({ status: "cancelled" });
  });
  it("rejects the wrong date or detaching a linked ticket without partial changes", async () => {
    await editApplication({ status: "approved" });
    await db.query("insert into ticket_instances values($1,'2026-09-13',null,6)", [tokenB]);
    await expect(editApplication({ ticketInstanceId: tokenB })).rejects.toThrow("같은 날짜");
    await expect(editApplication({ ticketInstanceId: null })).rejects.toThrow("취소 처리");
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("routes a linked participation update through its application", async () => {
    await editApplication({ status: "approved" });
    await editParticipation({ status: "cancelled", adminNote: "legacy entry" });
    expect((await db.query("select status,admin_note from meeting_date_applications")).rows[0])
      .toEqual({ status: "cancelled", admin_note: "legacy entry" });
  });
  it("moves a standalone participation without carrying the old venue snapshot", async () => {
    await db.query("insert into ticket_instances values($1,'2026-09-13',null,6)", [tokenB]);
    await editParticipation({ ticketInstanceId: tokenB, adminNote: "new venue" });
    expect((await db.query("select ticket_instance_id,ticket_snapshot,admin_note,status from ticket_participations where id=1")).rows[0])
      .toEqual({ ticket_instance_id: tokenB, ticket_snapshot: {}, admin_note: "new venue", status: "approved" });
  });
  it("rolls back a standalone move when the destination is full", async () => {
    await db.query("insert into ticket_instances values($1,'2026-09-13',null,0)", [tokenB]);
    await expect(editParticipation({ ticketInstanceId: tokenB, status: "approved", adminNote: "must rollback" })).rejects.toThrow("capacity");
    expect((await db.query("select ticket_instance_id,ticket_snapshot,admin_note from ticket_participations where id=1")).rows[0])
      .toEqual({ ticket_instance_id: instanceId, ticket_snapshot: { reservationName: "예약 유지" }, admin_note: null });
  });
  it("inherits the destination reservation name when moving to another venue", async () => {
    await db.query("insert into ticket_instances values($1,'2026-09-13',null,6)", [tokenB]);
    await db.query("insert into ticket_participations(user_id,ticket_instance_id,status,ticket_snapshot) values($1,$2,'approved',$3)",
      [tokenA, tokenB, JSON.stringify({ reservationName: "새 장소 예약" })]);
    await editParticipation({ ticketInstanceId: tokenB });
    expect((await db.query("select ticket_snapshot from ticket_participations where id=1")).rows[0])
      .toEqual({ ticket_snapshot: { reservationName: "새 장소 예약" } });
  });
  it("refuses to merge two existing standalone participation records", async () => {
    await db.query("insert into ticket_instances values($1,'2026-09-13',null,6)", [tokenB]);
    await db.query("insert into ticket_participations(user_id,ticket_instance_id,status) values($1,$2,'cancelled')", [userId,tokenB]);
    await expect(editParticipation({ ticketInstanceId: tokenB })).rejects.toThrow("이미 참가 기록");
    expect((await db.query("select ticket_instance_id from ticket_participations where id=1")).rows[0])
      .toEqual({ ticket_instance_id: instanceId });
  });
  it("executes the commands as service_role", async () => {
    await db.exec("set role service_role");
    try {
      await editApplication({ status: "approved" });
      await editParticipation({ status: "cancelled" });
    } finally { await db.exec("reset role"); }
    expect((await db.query("select status from meeting_date_applications")).rows[0]).toEqual({ status: "cancelled" });
  });
  it("rolls back an entire batch when one member is no longer eligible", async () => {
    await db.query("insert into meeting_date_applications(id,user_id,status) values(11,$1,'approved')", [tokenA]);
    await expect(batch([10,11],true)).rejects.toThrow("참여 확정 전");
    expect((await db.query("select status,ticket_participation_id from meeting_date_applications where id=10")).rows[0])
      .toEqual({ status: "waitlisted", ticket_participation_id: null });
  });
  it("rolls back approvals if confirming the group fails", async () => {
    await db.query("insert into meeting_groups(id,legacy_ticket_instance_id,status) values($1,$2,'draft')", [tokenA,instanceId]);
    await db.exec("alter table meeting_groups add constraint simulate_group_failure check(status <> 'confirmed')");
    try {
      await expect(batch([10],true)).rejects.toThrow();
      expect((await db.query("select status,ticket_participation_id from meeting_date_applications")).rows[0])
        .toEqual({ status: "waitlisted", ticket_participation_id: null });
    } finally { await db.exec("alter table meeting_groups drop constraint simulate_group_failure"); }
  });
  it("rechecks a group assignment after the operator's initial lookup", async () => {
    await db.query("update meeting_date_applications set assigned_ticket_instance_id=$1", [tokenB]);
    await expect(batch([10],true,true)).rejects.toThrow("그룹 배정이 변경");
  });
  it("distributes without approving and confirms the group atomically", async () => {
    await db.query("insert into meeting_groups(id,legacy_ticket_instance_id,status) values($1,$2,'draft')", [tokenA,instanceId]);
    await batch([10],false);
    expect((await db.query("select status,ticket_participation_id,assigned_group_id from meeting_date_applications")).rows[0])
      .toEqual({ status: "waitlisted", ticket_participation_id: null, assigned_group_id: tokenA });
    await batch([10],true,true);
    expect((await db.query("select status from meeting_groups")).rows[0]).toEqual({ status: "confirmed" });
  });
  it("blocks browser execution of every admin command", async () => {
    await db.exec("set role authenticated");
    try {
      await expect(editApplication({ status: "approved" })).rejects.toThrow("permission denied");
      await expect(editParticipation({ status: "approved" })).rejects.toThrow("permission denied");
      await expect(batch([10],true)).rejects.toThrow("permission denied");
    } finally { await db.exec("reset role"); }
  });
});

describe("webhook processing claims", () => {
  beforeEach(async () => { await db.exec("insert into groble_webhook_events(event_id,idempotency_key) values('event-1','key-1')"); });
  it("claims received events and refuses concurrent workers", async () => {
    expect((await claim()).outcome).toBe("claimed");
    expect((await claim(tokenB)).outcome).toBe("busy");
  });
  it("recovers a worker that stopped without writing failed", async () => {
    await claim();
    await db.exec("update groble_webhook_events set processing_lease_until=now()-interval '1 second'");
    expect((await claim(tokenB)).outcome).toBe("claimed");
    expect((await db.query("select processing_token from groble_webhook_events")).rows[0]).toEqual({ processing_token: tokenB });
  });
  it("retries failed events, but does not replay finished events", async () => {
    await db.exec("update groble_webhook_events set processing_status='failed'");
    expect((await claim()).outcome).toBe("claimed");
    await db.exec("update groble_webhook_events set processing_status='processed'");
    expect((await claim(tokenB)).outcome).toBe("done");
  });
  it("uses the stored key when the same event is redelivered with another key", async () => {
    expect(await claim(tokenA,"event-1","new-key")).toEqual({ outcome: "claimed", event_key: "key-1" });
  });
  it("rejects a key collision for another event", async () => {
    expect((await claim(tokenA,"event-2","key-1")).outcome).toBe("conflict");
  });
});
