import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

const userId = "00000000-0000-4000-8000-000000000001";
const instanceId = "00000000-0000-4000-8000-000000000002";
const tokenA = "00000000-0000-4000-8000-000000000003";
const tokenB = "00000000-0000-4000-8000-000000000004";
let db: PGlite;

beforeAll(async () => {
  db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table ticket_instances(id uuid primary key, event_date date, template_id uuid, max_participant_count int);
    create table ticket_participations(
      id bigint generated by default as identity primary key, user_id uuid, ticket_id text,
      ticket_template_id uuid, ticket_instance_id uuid, meeting_date date, status text,
      ticket_snapshot jsonb, invitation_id uuid, applied_at timestamptz, confirmed_at timestamptz,
      cancelled_at timestamptz, updated_at timestamptz, feedback_completed_at timestamptz);
    create table meeting_date_applications(id bigint primary key, user_id uuid, status text,
      assigned_ticket_instance_id uuid, ticket_participation_id bigint, updated_at timestamptz);
    create table meeting_feedback(waitlist_id bigint unique, user_id uuid, ticket_instance_id uuid,
      ticket_template_id uuid, ticket_snapshot jsonb, selected_member_ids uuid[], member_feedback jsonb,
      place_feedback jsonb, updated_at timestamptz);
    create table groble_webhook_events(id bigint generated always as identity primary key,
      event_id text unique, idempotency_key text unique, processing_status text default 'received', updated_at timestamptz);
    grant insert, update, select on meeting_feedback to authenticated;
    grant all on all tables in schema public to service_role;
    grant all on all sequences in schema public to service_role;
  `);
  const original = readFileSync("supabase/migrations/20260701100000_ticket_domain_restructure.sql", "utf8");
  const start = original.indexOf("create or replace function public.set_ticket_participation_status(");
  const end = original.indexOf("$$;", start) + 3;
  await db.exec(original.slice(start, end));
  for (const file of ["20260906031238_harden_feedback_and_application_writes.sql", "20260906031248_recover_interrupted_webhooks.sql"]) {
    await db.exec(readFileSync(`supabase/migrations/${file}`, "utf8"));
  }
}, 30_000);

beforeEach(async () => {
  await db.exec("truncate ticket_participations, meeting_date_applications, ticket_instances, meeting_feedback, groble_webhook_events restart identity;");
  await db.query("insert into ticket_instances values ($1, '2026-09-06', null, 6)", [instanceId]);
  await db.query("insert into ticket_participations(id,user_id,ticket_instance_id,status,ticket_snapshot) values (1,$1,$2,'approved', $3)", [userId, instanceId, JSON.stringify({ reservationName: "예약 유지" })]);
  await db.query("insert into meeting_date_applications(id,user_id,status,assigned_ticket_instance_id) values (10,$1,'waitlisted',$2)", [userId, instanceId]);
});
afterAll(async () => { await db?.close(); });

const ensure = () => db.query("select ensure_application_participation(10,$1,$2,'{}') as id", [userId, instanceId]);
const save = () => db.query("select save_validated_meeting_feedback(1,$1,$2,null,'{}','{}','{}','{}')", [userId, instanceId]);

describe("atomic participation and feedback writes", () => {
  it("preserves confirmed status and reservation snapshot on repeated application linking", async () => {
    await ensure(); await ensure();
    const row = (await db.query<{ status: string; ticket_snapshot: object }>("select status,ticket_snapshot from ticket_participations where id=1")).rows[0];
    expect(row).toEqual({ status: "approved", ticket_snapshot: { reservationName: "예약 유지" } });
    expect((await db.query("select ticket_participation_id from meeting_date_applications where id=10")).rows[0]).toEqual({ ticket_participation_id: 1 });
  });
  it("does not touch an application approved while the request was in flight", async () => {
    await db.exec("update meeting_date_applications set status='approved',ticket_participation_id=1");
    await ensure();
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "approved" });
  });
  it("rejects a different ticket without changing the application", async () => {
    await expect(db.query("select ensure_application_participation(10,$1,$2,'{}')", [userId, tokenB])).rejects.toThrow("mismatch");
    expect((await db.query("select ticket_participation_id from meeting_date_applications")).rows[0]).toEqual({ ticket_participation_id: null });
  });
  it("saves feedback and marks completion once", async () => {
    await save(); await save();
    expect((await db.query("select count(*)::int as count from meeting_feedback")).rows[0]).toEqual({ count: 1 });
    expect((await db.query("select status from ticket_participations")).rows[0]).toEqual({ status: "feedback_done" });
  });
  it("rolls back feedback if completion fails", async () => {
    await db.exec("alter table ticket_participations add constraint simulate_failure check(status <> 'feedback_done')");
    try {
      await expect(save()).rejects.toThrow();
      expect((await db.query("select count(*)::int as count from meeting_feedback")).rows[0]).toEqual({ count: 0 });
    } finally { await db.exec("alter table ticket_participations drop constraint simulate_failure"); }
  });
  it("blocks browser writes and direct invocation of server-only functions", async () => {
    await db.exec("set role authenticated");
    try {
      await expect(db.query("insert into meeting_feedback(waitlist_id,user_id) values(1,$1)", [userId])).rejects.toThrow("permission denied");
      await expect(db.query("update meeting_feedback set member_feedback='{}'")).rejects.toThrow("permission denied");
      await expect(save()).rejects.toThrow("permission denied");
      await expect(ensure()).rejects.toThrow("permission denied");
    } finally { await db.exec("reset role"); }
  });
});

const claim = async (token = tokenA, eventId = "event-1", key = "key-1") =>
  (await db.query<{ outcome: string; event_key: string | null }>("select * from claim_groble_webhook_event($1,$2,$3)", [eventId,key,token])).rows[0];

describe("webhook processing claims", () => {
  beforeEach(async () => { await db.exec("insert into groble_webhook_events(event_id,idempotency_key) values('event-1','key-1')"); });
  it("claims received events and refuses concurrent workers", async () => {
    expect((await claim()).outcome).toBe("claimed");
    expect((await claim(tokenB)).outcome).toBe("busy");
  });
  it("recovers a worker that stopped without writing failed", async () => {
    await claim();
    await db.exec("update groble_webhook_events set processing_lease_until=now()-interval '1 second'");
    expect((await claim(tokenB)).outcome).toBe("claimed");
    expect((await db.query("select processing_token from groble_webhook_events")).rows[0]).toEqual({ processing_token: tokenB });
  });
  it("retries failed events, but does not replay finished events", async () => {
    await db.exec("update groble_webhook_events set processing_status='failed'");
    expect((await claim()).outcome).toBe("claimed");
    await db.exec("update groble_webhook_events set processing_status='processed'");
    expect((await claim(tokenB)).outcome).toBe("done");
  });
  it("uses the stored key when the same event is redelivered with another key", async () => {
    expect(await claim(tokenA,"event-1","new-key")).toEqual({ outcome: "claimed", event_key: "key-1" });
  });
  it("rejects a key collision for another event", async () => {
    expect((await claim(tokenA,"event-2","key-1")).outcome).toBe("conflict");
  });
});
