-- Public products and internal operations are intentionally separate:
-- ticket_templates are reusable programs, meeting_events are public sale units,
-- and meeting_groups are private table/location assignments.

create table if not exists public.meeting_events (
  id uuid primary key default gen_random_uuid(),
  program_id uuid not null references public.ticket_templates(id) on delete restrict,
  title text not null,
  short_description text,
  event_date date not null,
  starts_at time not null,
  region text not null default '서울',
  visibility text not null default 'draft'
    check (visibility in ('draft', 'test_only', 'public', 'closed', 'archived')),
  application_opens_at timestamptz,
  application_closes_at timestamptz,
  capacity integer not null default 30 check (capacity > 0),
  confirmed_application_count integer not null default 0
    check (confirmed_application_count >= 0),
  price_amount integer not null default 0 check (price_amount >= 0),
  currency text not null default 'KRW',
  detail_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists meeting_events_program_date_time_uidx
on public.meeting_events(program_id, event_date, starts_at);

create index if not exists meeting_events_public_schedule_idx
on public.meeting_events(visibility, event_date, starts_at)
where visibility in ('public', 'test_only');

create table if not exists public.meeting_event_stages (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.meeting_events(id) on delete cascade,
  title text not null,
  stage_type text not null default 'activity'
    check (stage_type in ('meal', 'activity', 'feedback', 'other')),
  sequence integer not null check (sequence > 0),
  starts_at time,
  location_mode text not null default 'shared'
    check (location_mode in ('shared', 'group_specific', 'hidden')),
  place_name text,
  address text,
  place_payload jsonb,
  reveal_offset_minutes integer not null default 1440
    check (reveal_offset_minutes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, sequence)
);

create index if not exists meeting_event_stages_event_idx
on public.meeting_event_stages(event_id, sequence);

create table if not exists public.meeting_groups (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.meeting_events(id) on delete cascade,
  code text not null,
  title text not null,
  capacity integer not null default 6 check (capacity > 0),
  status text not null default 'draft'
    check (status in ('draft', 'ready', 'confirmed', 'cancelled')),
  operation_note text,
  legacy_ticket_instance_id uuid unique
    references public.ticket_instances(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, code)
);

create index if not exists meeting_groups_event_idx
on public.meeting_groups(event_id, status, code);

create table if not exists public.meeting_group_stage_locations (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.meeting_groups(id) on delete cascade,
  stage_id uuid not null references public.meeting_event_stages(id) on delete cascade,
  place_name text,
  address text,
  place_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(group_id, stage_id)
);

create table if not exists public.meeting_event_rejections (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.meeting_events(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(event_id, user_id)
);

alter table public.meeting_date_applications
  add column if not exists event_id uuid
    references public.meeting_events(id) on delete restrict,
  add column if not exists assigned_group_id uuid
    references public.meeting_groups(id) on delete set null;

create index if not exists meeting_date_applications_event_status_idx
on public.meeting_date_applications(event_id, status, created_at desc);

create index if not exists meeting_date_applications_group_idx
on public.meeting_date_applications(assigned_group_id)
where assigned_group_id is not null;

-- Preserve the current uniqueness rule while allowing multiple programs on one date.
alter table public.meeting_date_applications
drop constraint if exists meeting_date_applications_user_id_meeting_date_key;

create unique index if not exists meeting_date_applications_legacy_user_date_uidx
on public.meeting_date_applications(user_id, meeting_date)
where event_id is null;

create index if not exists meeting_date_applications_user_event_idx
on public.meeting_date_applications(user_id, event_id, created_at desc)
where event_id is not null;

alter table public.meeting_events enable row level security;
alter table public.meeting_event_stages enable row level security;
alter table public.meeting_groups enable row level security;
alter table public.meeting_group_stage_locations enable row level security;
alter table public.meeting_event_rejections enable row level security;

grant select, insert, update, delete on table public.meeting_events to service_role;
grant select, insert, update, delete on table public.meeting_event_stages to service_role;
grant select, insert, update, delete on table public.meeting_groups to service_role;
grant select, insert, update, delete on table public.meeting_group_stage_locations to service_role;
grant select, insert, update, delete on table public.meeting_event_rejections to service_role;
grant usage, select on sequence public.meeting_event_rejections_id_seq to service_role;

-- Convert each legacy program/date into one public event. Legacy detail tickets
-- become private groups, so two dinner locations no longer create two cards.
insert into public.meeting_events (
  program_id,
  title,
  short_description,
  event_date,
  starts_at,
  region,
  visibility,
  capacity,
  detail_snapshot
)
select
  template.id,
  template.title,
  template.short_description,
  instance.event_date,
  coalesce(instance.event_time, template.default_time, '18:00'::time),
  coalesce(min(instance.region), template.default_region, '서울'),
  case
    when bool_or(instance.visibility = 'public') then 'public'
    when bool_or(instance.visibility = 'test_only') then 'test_only'
    when bool_or(instance.visibility = 'closed') then 'closed'
    when bool_or(instance.visibility = 'archived') then 'archived'
    else 'draft'
  end,
  greatest(sum(instance.max_participant_count), 1)::integer,
  jsonb_build_object(
    'detailSummary', template.detail_summary,
    'detailActivities', template.detail_activities,
    'detailFlow', template.detail_flow,
    'detailGoodFor', template.detail_good_for,
    'detailNotice', template.detail_notice,
    'courseSteps', template.course_steps,
    'moodTags', template.mood_tags,
    'activityType', template.activity_type
  )
from public.ticket_instances instance
join public.ticket_templates template on template.id = instance.template_id
where instance.event_date is not null
  and template.template_kind = 'experience'
group by
  template.id,
  template.title,
  template.short_description,
  template.default_region,
  template.default_time,
  template.detail_summary,
  template.detail_activities,
  template.detail_flow,
  template.detail_good_for,
  template.detail_notice,
  template.course_steps,
  template.mood_tags,
  template.activity_type,
  instance.event_date,
  coalesce(instance.event_time, template.default_time, '18:00'::time)
on conflict (program_id, event_date, starts_at) do nothing;

insert into public.meeting_groups (
  event_id,
  code,
  title,
  capacity,
  status,
  operation_note,
  legacy_ticket_instance_id
)
select
  event.id,
  concat(
    coalesce(nullif(instance.operation_code, ''), 'G'),
    '-',
    left(instance.id::text, 6)
  ),
  coalesce(nullif(instance.operation_code, ''), instance.title),
  instance.max_participant_count,
  case
    when instance.visibility in ('public', 'test_only') then 'ready'
    when instance.visibility = 'closed' then 'confirmed'
    else 'draft'
  end,
  instance.operation_note,
  instance.id
from public.ticket_instances instance
join public.ticket_templates template on template.id = instance.template_id
join public.meeting_events event
  on event.program_id = instance.template_id
 and event.event_date = instance.event_date
 and event.starts_at = coalesce(instance.event_time, template.default_time, '18:00'::time)
where instance.event_date is not null
on conflict (legacy_ticket_instance_id) do nothing;

update public.meeting_date_applications application
set
  event_id = group_record.event_id,
  assigned_group_id = group_record.id
from public.meeting_groups group_record
where group_record.legacy_ticket_instance_id = application.assigned_ticket_instance_id
  and application.event_id is null;

update public.meeting_date_applications application
set event_id = candidate.event_id
from (
  select
    application_row.id as application_id,
    min(event.id::text)::uuid as event_id
  from public.meeting_date_applications application_row
  join public.meeting_events event on event.event_date = application_row.meeting_date
  where application_row.event_id is null
  group by application_row.id
  having count(*) = 1
) candidate
where application.id = candidate.application_id;

create or replace function public.refresh_meeting_event_application_count(
  p_event_id uuid
)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  update public.meeting_events event
  set confirmed_application_count = (
    select count(*)::integer
    from public.meeting_date_applications application
    where application.event_id = p_event_id
      and application.status in (
        'payment_pending',
        'waitlisted',
        'on_hold',
        'approved',
        'feedback_done',
        'completed'
      )
  ), updated_at = now()
  where event.id = p_event_id;
$$;

revoke all on function public.refresh_meeting_event_application_count(uuid)
from public, anon, authenticated;
grant execute on function public.refresh_meeting_event_application_count(uuid)
to service_role;

create or replace function public.sync_meeting_event_application_count()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op <> 'INSERT' and old.event_id is not null then
    perform public.refresh_meeting_event_application_count(old.event_id);
  end if;
  if tg_op <> 'DELETE' and new.event_id is not null then
    perform public.refresh_meeting_event_application_count(new.event_id);
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_meeting_event_application_count_trigger
on public.meeting_date_applications;
create trigger sync_meeting_event_application_count_trigger
after insert or update or delete
on public.meeting_date_applications
for each row execute function public.sync_meeting_event_application_count();

update public.meeting_events event
set confirmed_application_count = source.application_count
from (
  select
    application.event_id,
    count(*)::integer as application_count
  from public.meeting_date_applications application
  where application.event_id is not null
    and application.status in (
      'payment_pending',
      'waitlisted',
      'on_hold',
      'approved',
      'feedback_done',
      'completed'
    )
  group by application.event_id
) source
where source.event_id = event.id;

-- Fast, single-query read model for the application list. It deliberately
-- contains no group, participant, or place joins.
create or replace view public.public_meeting_events
with (security_invoker = true)
as
select
  event.id,
  event.program_id,
  event.title,
  event.short_description,
  event.event_date,
  event.starts_at,
  event.region,
  event.application_opens_at,
  event.application_closes_at,
  event.capacity,
  event.confirmed_application_count,
  event.price_amount,
  event.currency,
  event.detail_snapshot
from public.meeting_events event
where event.visibility = 'public';

revoke all on table public.public_meeting_events from public, anon, authenticated;
grant select on table public.public_meeting_events to service_role;
