create table if not exists public.meeting_date_applications (
  id bigint generated by default as identity primary key,
  application_group_id uuid not null default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meeting_date date not null,
  meeting_time time not null,
  region text not null default '서울',
  status text not null default 'payment_pending'
    check (
      status in (
        'payment_pending',
        'waitlisted',
        'on_hold',
        'approved',
        'not_selected',
        'cancelled',
        'feedback_done',
        'completed'
      )
    ),
  deposit_amount integer not null default 20000
    check (deposit_amount = 20000),
  deposit_status text not null default 'payment_pending'
    check (
      deposit_status in (
        'payment_pending',
        'confirmed',
        'refund_pending',
        'refunded',
        'forfeited'
      )
    ),
  deposit_requested_at timestamptz not null default now(),
  deposit_confirmed_at timestamptz,
  refund_completed_at timestamptz,
  assigned_ticket_instance_id uuid
    references public.ticket_instances(id) on delete set null,
  ticket_participation_id bigint
    references public.ticket_participations(id) on delete set null,
  assigned_at timestamptz,
  confirmed_at timestamptz,
  cancelled_at timestamptz,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, meeting_date)
);

create index if not exists meeting_date_applications_date_status_idx
on public.meeting_date_applications(meeting_date, status, created_at desc);

create index if not exists meeting_date_applications_user_status_idx
on public.meeting_date_applications(user_id, status, created_at desc);

create index if not exists meeting_date_applications_instance_idx
on public.meeting_date_applications(assigned_ticket_instance_id);

alter table public.meeting_date_applications enable row level security;

drop policy if exists "Users can read own meeting date applications"
on public.meeting_date_applications;

create policy "Users can read own meeting date applications"
on public.meeting_date_applications
for select
to authenticated
using (auth.uid() = user_id);

grant select on table public.meeting_date_applications to authenticated;
grant select, insert, update, delete
on table public.meeting_date_applications to service_role;
grant usage, select
on sequence public.meeting_date_applications_id_seq to service_role;
