alter table public.profiles
add column if not exists browse_seen_at timestamptz,
add column if not exists questions_completed boolean not null default false,
add column if not exists profile_completed boolean not null default false,
add column if not exists public_intro text,
add column if not exists public_intro_generated_at timestamptz,
add column if not exists public_intro_model text,
add column if not exists meeting_guidelines_agreed boolean not null default false,
add column if not exists meeting_guidelines_agreed_at timestamptz;

create table if not exists public.meeting_waitlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ticket_id text not null,
  meeting_date date not null,
  status text not null default 'waitlisted'
    check (status in ('waitlisted', 'approved', 'declined', 'cancelled')),
  ticket_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, ticket_id)
);

alter table public.meeting_waitlist enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'meeting_waitlist'
      and policyname = 'Users can read own meeting waitlist'
  ) then
    create policy "Users can read own meeting waitlist"
    on public.meeting_waitlist
    for select
    to authenticated
    using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'meeting_waitlist'
      and policyname = 'Users can join own meeting waitlist'
  ) then
    create policy "Users can join own meeting waitlist"
    on public.meeting_waitlist
    for insert
    to authenticated
    with check (
      auth.uid() = user_id
      and status = 'waitlisted'
    );
  end if;
end
$$;
