create table if not exists public.meeting_date_payment_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  application_id bigint not null
    references public.meeting_date_applications(id) on delete cascade,
  application_group_id uuid not null,
  meeting_date date not null,
  status text not null default 'active'
    check (status in ('active', 'superseded', 'expired', 'completed')),
  opened_at timestamptz not null default now(),
  ended_at timestamptz,
  expires_at timestamptz not null,
  completed_at timestamptz,
  groble_payment_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at is null or ended_at >= opened_at),
  check (expires_at > opened_at)
);

create unique index if not exists meeting_date_payment_intents_one_active_per_user_idx
on public.meeting_date_payment_intents(user_id)
where status = 'active' and ended_at is null;

create index if not exists meeting_date_payment_intents_user_interval_idx
on public.meeting_date_payment_intents(user_id, opened_at desc, expires_at);

create index if not exists meeting_date_payment_intents_application_group_idx
on public.meeting_date_payment_intents(application_group_id, opened_at desc);

alter table public.groble_webhook_events
add column if not exists matched_payment_intent_id bigint
references public.meeting_date_payment_intents(id) on delete set null;

create index if not exists groble_webhook_events_payment_intent_idx
on public.groble_webhook_events(matched_payment_intent_id)
where matched_payment_intent_id is not null;

alter table public.meeting_date_payment_intents enable row level security;

revoke all on table public.meeting_date_payment_intents from anon, authenticated;
grant select, insert, update on table public.meeting_date_payment_intents
to service_role;
grant usage, select on sequence public.meeting_date_payment_intents_id_seq
to service_role;

create or replace function public.activate_meeting_date_payment_intent(
  p_user_id uuid,
  p_application_id bigint
)
returns table (
  intent_id bigint,
  application_group_id uuid,
  opened_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  application_record public.meeting_date_applications%rowtype;
  intent_record public.meeting_date_payment_intents%rowtype;
  switched_at timestamptz := clock_timestamp();
begin
  select *
  into application_record
  from public.meeting_date_applications
  where id = p_application_id
    and user_id = p_user_id
    and deposit_status = 'payment_pending'
    and status in ('payment_pending', 'waitlisted', 'on_hold', 'approved')
  for update;

  if not found then
    raise exception 'Eligible meeting date application was not found.';
  end if;

  update public.meeting_date_payment_intents
  set
    status = case
      when expires_at <= switched_at then 'expired'
      else 'superseded'
    end,
    ended_at = least(switched_at, expires_at),
    updated_at = switched_at
  where user_id = p_user_id
    and status = 'active'
    and ended_at is null;

  insert into public.meeting_date_payment_intents (
    user_id,
    application_id,
    application_group_id,
    meeting_date,
    status,
    opened_at,
    expires_at,
    created_at,
    updated_at
  )
  values (
    p_user_id,
    application_record.id,
    application_record.application_group_id,
    application_record.meeting_date,
    'active',
    switched_at,
    switched_at + interval '60 minutes',
    switched_at,
    switched_at
  )
  returning * into intent_record;

  return query
  select
    intent_record.id,
    intent_record.application_group_id,
    intent_record.opened_at,
    intent_record.expires_at;
end;
$$;

revoke all on function public.activate_meeting_date_payment_intent(uuid, bigint)
from public, anon, authenticated;
grant execute on function public.activate_meeting_date_payment_intent(uuid, bigint)
to service_role;

create or replace function public.match_meeting_date_payment_intent(
  p_user_id uuid,
  p_paid_at timestamptz,
  p_amount integer
)
returns table (
  intent_id bigint,
  application_group_id uuid
)
language sql
stable
security definer
set search_path = public
as $$
  select
    intent.id as intent_id,
    intent.application_group_id
  from public.meeting_date_payment_intents intent
  join public.meeting_date_applications application
    on application.id = intent.application_id
   and application.user_id = intent.user_id
   and application.application_group_id = intent.application_group_id
  where intent.user_id = p_user_id
    and intent.opened_at <= p_paid_at
    and p_paid_at < intent.expires_at
    and (intent.ended_at is null or p_paid_at < intent.ended_at)
    and intent.status in ('active', 'superseded')
    and application.deposit_status = 'payment_pending'
    and application.deposit_amount = p_amount
    and application.status in ('payment_pending', 'waitlisted', 'on_hold', 'approved')
  order by intent.opened_at desc
  limit 2;
$$;

revoke all on function public.match_meeting_date_payment_intent(uuid, timestamptz, integer)
from public, anon, authenticated;
grant execute on function public.match_meeting_date_payment_intent(uuid, timestamptz, integer)
to service_role;
