alter table public.meeting_date_payment_intents
add column if not exists acquisition_context jsonb;

alter table public.meeting_date_payment_intents
drop constraint if exists meeting_date_payment_intents_acquisition_context_check;

alter table public.meeting_date_payment_intents
add constraint meeting_date_payment_intents_acquisition_context_check
check (
  acquisition_context is null
  or jsonb_typeof(acquisition_context) = 'object'
);

comment on column public.meeting_date_payment_intents.acquisition_context is
  'Sanitized acquisition fields captured at checkout, including Meta browser and click identifiers when available.';

comment on column public.membership_payment_intents.acquisition_context is
  'Sanitized acquisition fields captured at checkout, including Meta browser and click identifiers when available.';

create table if not exists public.meta_conversion_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_name text not null,
  source_provider text not null,
  source_event_id text not null,
  user_id uuid references public.profiles(user_id) on delete set null,
  payment_transaction_id bigint
    references public.payment_transactions(id) on delete set null,
  payload jsonb not null,
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'sent', 'failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_attempt_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  provider_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_provider, source_event_id, event_name)
);

create index if not exists meta_conversion_events_delivery_idx
on public.meta_conversion_events(delivery_status, created_at)
where delivery_status in ('pending', 'failed');

alter table public.meta_conversion_events enable row level security;

revoke all on table public.meta_conversion_events from anon, authenticated;
grant select, insert, update on table public.meta_conversion_events to service_role;
grant usage, select on sequence public.meta_conversion_events_id_seq to service_role;
