create table if not exists public.ticket_user_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ticket_instance_id uuid not null references public.ticket_instances(id) on delete cascade,
  ticket_template_id uuid not null references public.ticket_templates(id) on delete cascade,
  status text not null default 'open'
    check (status in ('open', 'no', 'yes', 'payment_pending', 'payment_confirmed')),
  opened_at timestamptz,
  responded_at timestamptz,
  payment_started_at timestamptz,
  payment_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, ticket_instance_id)
);

create index if not exists ticket_user_interactions_user_updated_idx
on public.ticket_user_interactions(user_id, updated_at desc);

create index if not exists ticket_user_interactions_ticket_status_idx
on public.ticket_user_interactions(ticket_instance_id, status, updated_at desc);

alter table public.ticket_user_interactions enable row level security;

drop policy if exists "Users can read own ticket interactions"
on public.ticket_user_interactions;
create policy "Users can read own ticket interactions"
on public.ticket_user_interactions
for select
to authenticated
using (auth.uid() = user_id);

grant select on table public.ticket_user_interactions to authenticated;
grant select, insert, update, delete on table public.ticket_user_interactions to service_role;
grant usage, select on sequence public.ticket_user_interactions_id_seq to service_role;
