alter table public.meeting_date_applications
  add column if not exists groble_merchant_uid text,
  add column if not exists groble_payment_event_id text,
  add column if not exists payment_cancel_requested_at timestamptz;

create index if not exists meeting_date_applications_groble_merchant_uid_idx
on public.meeting_date_applications(groble_merchant_uid)
where groble_merchant_uid is not null;

create table if not exists public.groble_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  idempotency_key text not null unique,
  event_type text not null,
  schema_version text,
  occurred_at timestamptz,
  merchant_uid text,
  buyer_phone_normalized text,
  matched_user_id uuid references auth.users(id) on delete set null,
  matched_application_group_id uuid,
  processing_status text not null default 'received'
    check (
      processing_status in (
        'received',
        'processed',
        'ignored',
        'unmatched',
        'ambiguous',
        'failed'
      )
    ),
  payload jsonb not null,
  last_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists groble_webhook_events_merchant_uid_idx
on public.groble_webhook_events(merchant_uid, received_at desc);

create index if not exists groble_webhook_events_status_idx
on public.groble_webhook_events(processing_status, received_at desc);

alter table public.groble_webhook_events enable row level security;

revoke all on table public.groble_webhook_events from anon, authenticated;
grant select, insert, update, delete
on table public.groble_webhook_events to service_role;
grant usage, select
on sequence public.groble_webhook_events_id_seq to service_role;

