create table if not exists public.membership_payment_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  plan text not null
    check (plan in ('one_month', 'three_months', 'six_months')),
  expected_amount integer not null check (expected_amount > 0),
  credit_amount integer not null default 0 check (credit_amount >= 0),
  status text not null default 'active'
    check (status in ('active', 'superseded', 'expired', 'completed', 'cancelled')),
  opened_at timestamptz not null default now(),
  ended_at timestamptz,
  expires_at timestamptz not null,
  completed_at timestamptz,
  groble_payment_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at is null or ended_at >= opened_at),
  check (expires_at > opened_at)
);

create unique index if not exists membership_payment_intents_one_active_per_user_idx
on public.membership_payment_intents(user_id)
where status = 'active' and ended_at is null;

create index if not exists membership_payment_intents_user_interval_idx
on public.membership_payment_intents(user_id, opened_at desc, expires_at);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  merchant_uid text,
  user_id uuid references public.profiles(user_id) on delete set null,
  payment_kind text not null
    check (
      payment_kind in (
        'one_time',
        'membership_initial',
        'membership_upgrade',
        'membership_renewal',
        'unknown'
      )
    ),
  product_code text not null,
  amount integer not null check (amount >= 0),
  currency text not null default 'KRW',
  status text not null default 'completed'
    check (
      status in (
        'completed',
        'cancel_requested',
        'cancelled',
        'refunded'
      )
    ),
  occurred_at timestamptz not null,
  cancel_requested_at timestamptz,
  cancelled_at timestamptz,
  application_group_id uuid,
  membership_payment_intent_id bigint
    references public.membership_payment_intents(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists payment_transactions_user_occurred_idx
on public.payment_transactions(user_id, occurred_at desc);

create index if not exists payment_transactions_kind_occurred_idx
on public.payment_transactions(payment_kind, occurred_at desc);

create index if not exists payment_transactions_merchant_uid_idx
on public.payment_transactions(provider, merchant_uid)
where merchant_uid is not null;

alter table public.groble_webhook_events
  add column if not exists matched_membership_payment_intent_id bigint
    references public.membership_payment_intents(id) on delete set null,
  add column if not exists payment_kind text,
  add column if not exists payment_amount integer;

create index if not exists groble_webhook_events_membership_intent_idx
on public.groble_webhook_events(matched_membership_payment_intent_id)
where matched_membership_payment_intent_id is not null;

alter table public.membership_payment_intents enable row level security;
alter table public.payment_transactions enable row level security;

revoke all on table public.membership_payment_intents from anon, authenticated;
revoke all on table public.payment_transactions from anon, authenticated;
grant select, insert, update on table public.membership_payment_intents
to service_role;
grant select, insert, update on table public.payment_transactions
to service_role;
grant usage, select on sequence public.membership_payment_intents_id_seq
to service_role;
grant usage, select on sequence public.payment_transactions_id_seq
to service_role;

create or replace function public.activate_membership_payment_intent(
  p_user_id uuid,
  p_plan text,
  p_expected_amount integer,
  p_credit_amount integer default 0
)
returns table (
  intent_id bigint,
  opened_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  intent_record public.membership_payment_intents%rowtype;
  switched_at timestamptz := clock_timestamp();
begin
  if p_plan not in ('one_month', 'three_months', 'six_months') then
    raise exception 'Unsupported membership plan.';
  end if;
  if p_expected_amount <= 0 or p_credit_amount < 0 then
    raise exception 'Invalid membership payment amount.';
  end if;

  update public.membership_payment_intents as intent
  set
    status = case
      when intent.expires_at <= switched_at then 'expired'
      else 'superseded'
    end,
    ended_at = least(switched_at, intent.expires_at),
    updated_at = switched_at
  where intent.user_id = p_user_id
    and intent.status = 'active'
    and intent.ended_at is null;

  insert into public.membership_payment_intents (
    user_id,
    plan,
    expected_amount,
    credit_amount,
    status,
    opened_at,
    expires_at,
    created_at,
    updated_at
  )
  values (
    p_user_id,
    p_plan,
    p_expected_amount,
    p_credit_amount,
    'active',
    switched_at,
    switched_at + interval '2 hours',
    switched_at,
    switched_at
  )
  returning * into intent_record;

  return query
  select intent_record.id, intent_record.opened_at, intent_record.expires_at;
end;
$$;

revoke all on function public.activate_membership_payment_intent(
  uuid,
  text,
  integer,
  integer
) from public, anon, authenticated;
grant execute on function public.activate_membership_payment_intent(
  uuid,
  text,
  integer,
  integer
) to service_role;

create or replace function public.match_membership_payment_intent(
  p_user_id uuid,
  p_paid_at timestamptz,
  p_amount integer
)
returns table (
  intent_id bigint,
  plan text,
  credit_amount integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    intent.id as intent_id,
    intent.plan,
    intent.credit_amount
  from public.membership_payment_intents as intent
  where intent.user_id = p_user_id
      and (
        intent.expected_amount = p_amount
        or (
          intent.credit_amount > 0
          and intent.expected_amount - intent.credit_amount = p_amount
        )
      )
    and intent.opened_at <= p_paid_at
    and p_paid_at < intent.expires_at
    and (intent.ended_at is null or p_paid_at < intent.ended_at)
    and intent.status in ('active', 'superseded')
  order by intent.opened_at desc
  limit 2;
$$;

revoke all on function public.match_membership_payment_intent(
  uuid,
  timestamptz,
  integer
) from public, anon, authenticated;
grant execute on function public.match_membership_payment_intent(
  uuid,
  timestamptz,
  integer
) to service_role;

insert into public.payment_transactions (
  provider,
  provider_event_id,
  merchant_uid,
  user_id,
  payment_kind,
  product_code,
  amount,
  status,
  occurred_at,
  application_group_id
)
select
  'groble',
  webhook.event_id,
  webhook.merchant_uid,
  webhook.matched_user_id,
  'one_time',
  'meeting_date_ticket',
  application.deposit_amount,
  'completed',
  coalesce(webhook.occurred_at, webhook.received_at),
  webhook.matched_application_group_id
from public.groble_webhook_events as webhook
join public.meeting_date_applications as application
  on application.application_group_id = webhook.matched_application_group_id
 and application.user_id = webhook.matched_user_id
where webhook.event_type = 'payment.completed'
  and webhook.processing_status = 'processed'
  and webhook.matched_user_id is not null
  and webhook.matched_application_group_id is not null
on conflict (provider, provider_event_id) do nothing;
